extern unsigned int var_12;
extern signed char var_13;
extern unsigned long long int var_14;
extern unsigned long long int var_15;
extern long long int var_16;
extern signed char var_17;
extern unsigned int var_18;
extern signed char var_19;
extern unsigned short var_20;
extern _Bool var_21;
extern signed char var_22;
extern unsigned long long int var_23;
extern long long int var_24;
extern unsigned short var_25;
extern signed char arr_2 [23] ;
extern long long int arr_3 [23] ;
extern unsigned char arr_4 [23] ;
extern long long int arr_11 [16] ;
extern unsigned int arr_19 [16] ;
extern unsigned char arr_20 [16] ;
extern unsigned int arr_21 [16] [16] [16] [16] ;
