extern unsigned long long int var_11;
extern unsigned long long int var_12;
extern unsigned long long int var_13;
extern unsigned long long int var_14;
extern unsigned long long int var_15;
extern unsigned long long int var_16;
extern unsigned long long int var_17;
extern unsigned long long int var_18;
extern unsigned long long int var_19;
extern unsigned long long int var_20;
extern unsigned long long int var_21;
extern unsigned long long int var_22;
extern unsigned long long int var_23;
extern unsigned long long int var_24;
extern unsigned long long int var_25;
extern unsigned long long int var_26;
extern unsigned long long int var_27;
extern unsigned long long int var_28;
extern unsigned long long int var_29;
extern unsigned long long int var_30;
extern unsigned long long int var_31;
extern unsigned long long int var_32;
extern unsigned long long int var_33;
extern unsigned long long int var_34;
extern unsigned long long int var_35;
extern unsigned long long int var_36;
extern unsigned long long int var_37;
extern unsigned long long int var_38;
extern unsigned long long int var_39;
extern unsigned long long int var_40;
extern unsigned long long int var_41;
extern unsigned long long int var_42;
extern unsigned long long int var_43;
extern unsigned long long int var_44;
extern unsigned long long int var_45;
extern unsigned long long int var_46;
extern unsigned long long int var_47;
extern unsigned long long int var_48;
extern unsigned long long int var_49;
extern unsigned long long int var_50;
extern unsigned long long int var_51;
extern unsigned long long int var_52;
extern unsigned long long int var_53;
extern unsigned long long int var_54;
extern unsigned long long int var_55;
extern unsigned long long int var_56;
extern unsigned long long int var_57;
extern unsigned long long int var_58;
extern unsigned long long int var_59;
extern unsigned long long int var_60;
extern unsigned long long int var_61;
extern unsigned long long int var_62;
extern unsigned long long int var_63;
extern unsigned long long int var_64;
extern unsigned long long int var_65;
extern unsigned long long int var_66;
extern unsigned long long int var_67;
extern unsigned long long int var_68;
extern unsigned long long int var_69;
extern unsigned long long int var_70;
extern unsigned long long int var_71;
extern unsigned long long int var_72;
extern unsigned long long int var_73;
extern unsigned long long int var_74;
extern unsigned long long int var_75;
extern unsigned long long int var_76;
extern unsigned long long int var_77;
extern unsigned long long int var_78;
extern unsigned long long int var_79;
extern unsigned long long int var_80;
extern unsigned long long int var_81;
extern unsigned long long int var_82;
extern unsigned long long int var_83;
extern unsigned long long int var_84;
extern unsigned long long int var_85;
extern unsigned long long int var_86;
extern unsigned long long int var_87;
extern unsigned long long int var_88;
extern unsigned long long int var_89;
extern unsigned long long int var_90;
extern unsigned long long int var_91;
extern unsigned long long int var_92;
extern unsigned long long int var_93;
extern unsigned long long int var_94;
extern unsigned long long int arr_2 [13] ;
extern unsigned long long int arr_17 [14] [14] [14] ;
extern unsigned long long int arr_23 [14] [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_27 [14] [14] [14] ;
extern unsigned long long int arr_35 [14] [14] [14] ;
extern unsigned long long int arr_36 [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_41 [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_42 [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_57 [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_58 [14] [14] ;
extern unsigned long long int arr_62 [14] [14] [14] ;
extern unsigned long long int arr_65 [14] [14] ;
extern unsigned long long int arr_77 [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_84 [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_85 [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_86 [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_91 [14] ;
extern unsigned long long int arr_92 [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_93 [14] [14] [14] [14] [14] [14] ;
extern unsigned long long int arr_100 [14] [14] [14] [14] ;
extern unsigned long long int arr_101 [14] [14] [14] [14] ;
extern unsigned long long int arr_106 [14] ;
extern unsigned long long int arr_113 [14] [14] [14] ;
extern unsigned long long int arr_116 [14] ;
