extern unsigned char var_15;
extern long long int var_16;
extern unsigned char var_17;
extern _Bool var_18;
extern int var_19;
extern int var_20;
extern unsigned char var_21;
extern int var_22;
extern _Bool var_23;
extern unsigned char var_24;
extern unsigned long long int var_25;
extern long long int arr_17 [15] [15] ;
