extern long long int var_20;
extern signed char var_21;
extern unsigned char var_22;
extern signed char var_23;
extern unsigned long long int var_24;
extern unsigned long long int var_25;
extern signed char var_26;
extern long long int arr_2 [12] [12] ;
extern int arr_5 [20] ;
extern signed char arr_8 [20] ;
extern unsigned long long int arr_9 [20] ;
extern unsigned int arr_10 [20] ;
extern unsigned int arr_11 [20] ;
extern signed char arr_14 [20] [20] ;
