extern unsigned int var_13;
extern long long int var_14;
extern unsigned long long int var_15;
extern unsigned char var_16;
extern unsigned long long int var_17;
extern unsigned char var_18;
extern unsigned char arr_4 [19] [19] [19] ;
extern int arr_7 [15] [15] ;
extern unsigned char arr_8 [15] ;
extern unsigned int arr_9 [15] ;
extern long long int arr_10 [15] ;
extern short arr_14 [15] ;
