extern long long int var_19;
extern _Bool var_20;
extern signed char var_21;
extern _Bool var_22;
extern unsigned short var_23;
extern unsigned long long int var_24;
extern unsigned char var_25;
extern signed char var_26;
extern signed char var_27;
extern short var_28;
extern unsigned long long int var_29;
extern short arr_16 [19] [19] [19] [19] [19] ;
extern _Bool arr_17 [19] ;
