extern unsigned long long int var_12;
extern unsigned long long int var_13;
extern int var_14;
extern signed char var_15;
extern unsigned int var_16;
extern unsigned short var_17;
extern unsigned char var_18;
extern _Bool var_19;
extern short var_20;
extern unsigned short var_21;
extern int var_22;
extern int var_23;
extern signed char var_24;
extern _Bool var_25;
extern int var_26;
extern long long int var_27;
extern int arr_3 [23] [23] ;
extern unsigned long long int arr_11 [23] [23] ;
extern long long int arr_16 [16] [16] ;
extern unsigned char arr_17 [16] [16] ;
