extern unsigned short var_16;
extern unsigned short var_17;
extern unsigned short var_18;
extern unsigned short var_19;
extern unsigned short var_20;
extern unsigned short var_21;
extern unsigned short var_22;
extern unsigned short var_23;
extern unsigned short var_24;
