extern unsigned char var_20;
extern unsigned long long int var_21;
extern unsigned int var_22;
extern unsigned long long int var_23;
extern signed char var_24;
extern signed char var_25;
extern unsigned long long int var_26;
extern unsigned char var_27;
extern unsigned char var_28;
extern unsigned long long int var_29;
extern signed char var_30;
extern unsigned char var_31;
extern int var_32;
extern int var_33;
extern unsigned char var_34;
extern unsigned long long int var_35;
extern short arr_4 [14] ;
extern long long int arr_13 [23] [23] [23] [23] ;
extern _Bool arr_14 [23] ;
