extern short var_14;
extern short var_15;
extern short var_16;
extern unsigned int var_17;
extern unsigned int var_18;
extern long long int var_19;
extern long long int var_20;
extern long long int var_21;
extern _Bool var_22;
extern unsigned long long int var_23;
extern unsigned long long int var_24;
extern unsigned long long int var_25;
extern unsigned int var_26;
extern short var_27;
extern unsigned int arr_8 [23] ;
extern unsigned char arr_13 [24] [24] ;
extern long long int arr_14 [24] ;
