extern signed char var_16;
extern unsigned long long int var_17;
extern unsigned char var_18;
extern signed char var_19;
extern unsigned long long int var_20;
extern unsigned short var_21;
extern short var_22;
extern _Bool var_23;
extern long long int var_24;
extern unsigned long long int var_25;
extern unsigned long long int var_26;
extern unsigned int var_27;
extern short var_28;
extern _Bool var_29;
extern unsigned char var_30;
extern _Bool var_31;
extern long long int var_32;
extern unsigned int var_33;
extern int var_34;
extern long long int var_35;
extern unsigned long long int var_36;
extern _Bool var_37;
extern signed char var_38;
extern int var_39;
extern int var_40;
extern unsigned long long int var_41;
extern unsigned short var_42;
extern signed char var_43;
extern int arr_6 [18] [18] [18] [18] ;
