extern unsigned long long int var_16;
extern unsigned char var_17;
extern unsigned int var_18;
extern long long int var_19;
extern long long int var_20;
extern unsigned char var_21;
extern long long int var_22;
extern long long int var_23;
extern unsigned char var_24;
extern unsigned long long int var_25;
extern unsigned char arr_4 [17] [17] [17] ;
extern unsigned char arr_5 [17] [17] ;
