extern unsigned char var_17;
extern unsigned short var_18;
extern unsigned char var_19;
extern unsigned short var_20;
extern long long int var_21;
extern signed char var_22;
extern signed char var_23;
extern unsigned short var_24;
extern signed char var_25;
extern unsigned char var_26;
extern _Bool var_27;
extern unsigned int var_28;
extern unsigned short var_29;
extern signed char var_30;
extern unsigned short var_31;
extern unsigned int var_32;
extern long long int var_33;
extern int var_34;
extern unsigned char var_35;
extern short var_36;
extern unsigned int var_37;
extern unsigned short arr_4 [24] [24] ;
extern unsigned short arr_7 [15] ;
extern unsigned int arr_14 [15] [15] [15] [15] [15] [15] ;
extern int arr_17 [12] [12] ;
