extern unsigned long long int var_17;
extern unsigned short var_18;
extern short var_19;
extern unsigned char var_20;
extern _Bool var_21;
extern unsigned short var_22;
extern long long int var_23;
extern long long int var_24;
extern signed char arr_2 [20] ;
extern unsigned int arr_10 [18] ;
extern unsigned char arr_11 [18] [18] ;
extern unsigned char arr_12 [18] ;
extern _Bool arr_16 [18] ;
extern unsigned char arr_17 [18] ;
