extern unsigned long long int var_16;
extern unsigned int var_17;
extern unsigned short var_18;
extern unsigned short var_19;
extern unsigned char var_20;
extern unsigned int var_21;
extern signed char var_22;
extern unsigned long long int var_23;
extern long long int arr_8 [25] [25] [25] [25] ;
extern unsigned short arr_9 [25] [25] ;
extern unsigned char arr_10 [25] [25] [25] ;
