extern unsigned char var_10;
extern _Bool var_11;
extern signed char var_12;
extern unsigned long long int var_13;
extern long long int var_14;
extern unsigned int var_15;
extern unsigned char var_16;
extern unsigned int var_17;
extern short var_18;
extern short var_19;
extern unsigned int var_20;
extern unsigned short var_21;
extern _Bool var_22;
extern signed char arr_9 [14] ;
