extern _Bool var_18;
extern unsigned int var_19;
extern int var_20;
extern short var_21;
extern unsigned char var_22;
extern unsigned short var_23;
extern int var_24;
extern _Bool var_25;
extern short var_26;
extern signed char var_27;
extern short arr_5 [11] ;
extern short arr_9 [13] ;
