extern unsigned char var_19;
extern unsigned char var_20;
extern short var_21;
extern int var_22;
extern long long int var_23;
extern int var_24;
extern unsigned long long int var_25;
extern long long int var_26;
extern unsigned long long int var_27;
extern unsigned char var_28;
extern unsigned char var_29;
extern unsigned short var_30;
extern long long int arr_2 [13] ;
extern _Bool arr_5 [23] ;
