extern signed char var_17;
extern int var_18;
extern unsigned short var_19;
extern unsigned char var_20;
extern long long int var_21;
extern unsigned char var_22;
extern unsigned char var_23;
extern unsigned long long int var_24;
extern int var_25;
extern unsigned char var_26;
extern unsigned long long int var_27;
extern unsigned short arr_2 [15] ;
extern signed char arr_5 [15] ;
