extern unsigned short var_19;
extern unsigned short var_20;
extern unsigned short var_21;
extern unsigned short var_22;
extern unsigned short var_23;
extern unsigned short var_24;
extern unsigned short var_25;
extern unsigned short var_26;
extern unsigned short var_27;
extern unsigned short var_28;
extern unsigned short var_29;
extern unsigned short var_30;
extern unsigned short var_31;
extern unsigned short var_32;
extern unsigned short var_33;
extern unsigned short var_34;
extern unsigned short var_35;
extern unsigned short var_36;
extern unsigned short var_37;
extern unsigned short var_38;
extern unsigned short var_39;
extern unsigned short var_40;
extern unsigned short var_41;
extern unsigned short var_42;
extern unsigned short var_43;
extern unsigned short var_44;
extern unsigned short var_45;
extern unsigned short arr_6 [25] [25] [25] ;
extern unsigned short arr_7 [25] ;
extern unsigned short arr_10 [20] ;
extern unsigned short arr_11 [20] ;
extern unsigned short arr_14 [21] [21] ;
extern unsigned short arr_15 [21] ;
extern unsigned short arr_30 [10] [10] [10] [10] [10] ;
extern unsigned short arr_31 [10] [10] [10] [10] ;
extern unsigned short arr_32 [10] [10] [10] ;
