extern long long int var_11;
extern unsigned long long int var_12;
extern unsigned int var_13;
extern unsigned short var_14;
extern unsigned long long int var_15;
extern long long int var_16;
extern int var_17;
extern unsigned int var_18;
extern short var_19;
extern unsigned long long int arr_5 [13] ;
