extern unsigned short var_17;
extern _Bool var_18;
extern _Bool var_19;
extern short var_20;
extern unsigned int var_21;
extern _Bool var_22;
extern short var_23;
extern long long int var_24;
extern unsigned int var_25;
extern unsigned short var_26;
extern int var_27;
extern int var_28;
extern signed char var_29;
extern short var_30;
extern unsigned short var_31;
extern unsigned long long int var_32;
extern unsigned char var_33;
extern unsigned long long int var_34;
extern unsigned char var_35;
extern short var_36;
extern unsigned short var_37;
extern _Bool var_38;
extern _Bool var_39;
extern unsigned char var_40;
extern unsigned char var_41;
extern int var_42;
extern unsigned char var_43;
extern short var_44;
extern _Bool var_45;
extern unsigned short var_46;
extern unsigned short var_47;
extern short var_48;
extern unsigned char var_49;
extern int var_50;
extern signed char var_51;
extern signed char var_52;
extern unsigned char var_53;
extern _Bool var_54;
extern unsigned short var_55;
extern _Bool var_56;
extern short var_57;
extern _Bool var_58;
extern short var_59;
extern unsigned int var_60;
extern unsigned short var_61;
extern short var_62;
extern unsigned short var_63;
extern int var_64;
extern _Bool var_65;
extern _Bool var_66;
extern _Bool var_67;
extern _Bool var_68;
extern unsigned short var_69;
extern long long int var_70;
