extern unsigned long long int var_10;
extern _Bool var_11;
extern unsigned short var_12;
extern unsigned char var_13;
extern unsigned short var_14;
extern unsigned char var_15;
extern int var_16;
extern short var_17;
extern short var_18;
extern signed char var_19;
extern unsigned short var_20;
extern int var_21;
extern unsigned long long int var_22;
extern _Bool var_23;
extern signed char var_24;
extern _Bool var_25;
extern short var_26;
extern unsigned int var_27;
extern unsigned int var_28;
extern unsigned int var_29;
extern int var_30;
extern int var_31;
