extern unsigned long long int var_13;
extern short var_14;
extern long long int var_15;
extern unsigned char var_16;
extern unsigned int var_17;
extern unsigned int var_18;
extern long long int var_19;
extern unsigned int var_20;
extern unsigned int var_21;
extern short var_22;
extern unsigned int var_23;
extern unsigned int var_24;
extern unsigned int var_25;
extern long long int arr_16 [18] [18] [18] [18] ;
extern unsigned int arr_23 [25] ;
