extern int var_10;
extern unsigned short var_11;
extern _Bool var_12;
extern short var_13;
extern unsigned char var_14;
extern unsigned char var_15;
extern int var_16;
extern short var_17;
extern unsigned int var_18;
extern unsigned char var_19;
extern unsigned int var_20;
extern unsigned int var_21;
extern signed char var_22;
extern int var_23;
extern _Bool var_24;
extern unsigned char var_25;
extern signed char var_26;
extern unsigned int var_27;
extern unsigned int var_28;
extern long long int var_29;
extern short var_30;
extern unsigned int var_31;
extern unsigned char var_32;
extern long long int var_33;
extern unsigned char var_34;
extern int var_35;
extern unsigned int var_36;
extern unsigned short var_37;
extern unsigned int var_38;
extern signed char var_39;
extern unsigned int var_40;
extern unsigned short var_41;
extern unsigned int var_42;
extern _Bool var_43;
extern int var_44;
extern long long int var_45;
extern unsigned char var_46;
extern unsigned int var_47;
extern signed char var_48;
extern unsigned long long int var_49;
extern unsigned char var_50;
extern unsigned int var_51;
extern unsigned long long int var_52;
extern signed char var_53;
extern unsigned int var_54;
extern unsigned long long int var_55;
extern _Bool var_56;
extern signed char var_57;
extern unsigned long long int var_58;
extern signed char var_59;
extern unsigned short var_60;
extern signed char var_61;
extern int var_62;
extern unsigned int var_63;
extern unsigned char var_64;
extern unsigned short var_65;
extern unsigned long long int var_66;
extern signed char var_67;
extern unsigned int var_68;
extern long long int var_69;
extern long long int var_70;
extern long long int var_71;
extern unsigned long long int var_72;
extern short var_73;
extern unsigned char var_74;
extern signed char var_75;
extern signed char var_76;
extern long long int var_77;
extern _Bool var_78;
extern unsigned long long int var_79;
extern unsigned char var_80;
extern long long int var_81;
extern int var_82;
extern unsigned short var_83;
extern unsigned long long int var_84;
extern unsigned char var_85;
extern int var_86;
extern unsigned int var_87;
extern signed char var_88;
extern _Bool var_89;
extern unsigned char var_90;
extern signed char var_91;
extern unsigned char var_92;
extern unsigned char var_93;
extern unsigned short var_94;
extern unsigned int var_95;
extern unsigned char var_96;
extern signed char var_97;
extern int var_98;
extern int var_99;
extern _Bool var_100;
extern unsigned long long int var_101;
extern long long int var_102;
extern unsigned int var_103;
extern unsigned long long int var_104;
extern unsigned short var_105;
extern unsigned short var_106;
extern unsigned short var_107;
extern int var_108;
extern unsigned int var_109;
extern unsigned char var_110;
extern int var_111;
extern unsigned char var_112;
extern _Bool var_113;
extern unsigned long long int var_114;
extern unsigned int var_115;
extern unsigned int var_116;
extern int var_117;
extern signed char var_118;
extern unsigned int var_119;
extern unsigned int var_120;
extern long long int var_121;
extern unsigned long long int var_122;
extern long long int var_123;
extern unsigned char var_124;
extern int var_125;
extern unsigned long long int var_126;
extern signed char var_127;
extern unsigned int var_128;
extern _Bool var_129;
extern unsigned short var_130;
extern unsigned long long int var_131;
extern unsigned short var_132;
extern signed char var_133;
extern unsigned char var_134;
extern unsigned char var_135;
extern signed char var_136;
extern unsigned char var_137;
extern unsigned int var_138;
extern unsigned int var_139;
extern short var_140;
extern _Bool var_141;
extern unsigned char var_142;
extern long long int var_143;
extern unsigned char var_144;
extern signed char var_145;
extern signed char var_146;
extern signed char var_147;
extern unsigned long long int var_148;
extern signed char var_149;
extern unsigned char var_150;
extern unsigned short var_151;
extern unsigned short var_152;
extern unsigned short var_153;
extern unsigned int var_154;
extern _Bool var_155;
extern unsigned short var_156;
extern short var_157;
extern int var_158;
extern signed char var_159;
extern long long int var_160;
extern int var_161;
extern unsigned short var_162;
extern unsigned int var_163;
extern unsigned char var_164;
extern signed char var_165;
extern unsigned long long int var_166;
extern unsigned long long int var_167;
extern unsigned short var_168;
extern unsigned char var_169;
extern signed char var_170;
extern short var_171;
