extern unsigned int var_11;
extern unsigned long long int var_12;
extern _Bool var_13;
extern signed char var_14;
extern unsigned short var_15;
extern int var_16;
extern short var_17;
extern unsigned long long int var_18;
extern unsigned char var_19;
extern unsigned char var_20;
extern _Bool var_21;
