extern long long int var_11;
extern unsigned long long int var_12;
extern unsigned char var_13;
extern _Bool var_14;
extern _Bool var_15;
extern unsigned long long int var_16;
extern _Bool var_17;
extern long long int var_18;
extern long long int var_19;
extern long long int var_20;
extern signed char var_21;
extern long long int var_22;
extern signed char var_23;
extern unsigned char var_24;
extern signed char var_25;
extern _Bool var_26;
extern long long int var_27;
extern unsigned long long int var_28;
extern long long int var_29;
extern signed char var_30;
extern signed char var_31;
extern long long int var_32;
extern unsigned long long int arr_4 [22] [22] ;
extern _Bool arr_5 [22] [22] ;
extern _Bool arr_6 [22] [22] [22] ;
extern unsigned char arr_15 [17] [17] ;
