extern int var_15;
extern long long int var_16;
extern unsigned short var_17;
extern unsigned int var_18;
extern long long int var_19;
extern long long int var_20;
extern long long int var_21;
extern signed char var_22;
extern unsigned char var_23;
extern unsigned char var_24;
extern unsigned char var_25;
