extern _Bool var_10;
extern _Bool var_11;
extern int var_12;
extern signed char var_13;
extern unsigned char var_14;
extern unsigned char var_15;
extern unsigned long long int var_16;
extern int var_17;
extern signed char var_18;
extern unsigned short var_19;
extern signed char var_20;
extern unsigned short var_21;
extern unsigned char var_22;
extern unsigned long long int var_23;
extern unsigned int var_24;
extern long long int var_25;
extern int var_26;
extern _Bool arr_2 [11] ;
extern signed char arr_3 [11] [11] ;
extern unsigned int arr_9 [25] ;
extern short arr_21 [15] ;
