extern unsigned long long int var_15;
extern short var_16;
extern long long int var_17;
extern signed char var_18;
extern unsigned char var_19;
extern long long int var_20;
extern unsigned char var_21;
extern unsigned char var_22;
extern long long int var_23;
extern unsigned short var_24;
extern unsigned long long int var_25;
extern unsigned char var_26;
extern unsigned int arr_13 [23] ;
extern unsigned char arr_16 [23] ;
