extern unsigned long long int var_16;
extern unsigned long long int var_17;
extern _Bool var_18;
extern long long int var_19;
extern _Bool var_20;
extern unsigned int var_21;
extern unsigned char var_22;
extern unsigned char var_23;
extern unsigned long long int var_24;
extern short var_25;
extern unsigned long long int var_26;
extern unsigned long long int var_27;
extern unsigned short var_28;
extern unsigned long long int var_29;
extern unsigned char var_30;
extern int var_31;
extern _Bool var_32;
extern short var_33;
extern unsigned long long int var_34;
extern unsigned short var_35;
extern unsigned short var_36;
extern short var_37;
extern unsigned int var_38;
extern unsigned long long int var_39;
extern unsigned long long int var_40;
extern unsigned int var_41;
extern int var_42;
extern unsigned int arr_4 [21] [21] [21] ;
extern unsigned int arr_5 [21] [21] [21] ;
extern signed char arr_11 [21] [21] [21] ;
extern unsigned char arr_22 [14] [14] [14] ;
