extern unsigned short var_14;
extern short var_15;
extern _Bool var_16;
extern short var_17;
extern short var_18;
extern long long int var_19;
extern int var_20;
extern short var_21;
extern unsigned char var_22;
extern unsigned short var_23;
extern long long int var_24;
extern signed char var_25;
extern long long int var_26;
extern unsigned short var_27;
extern unsigned short var_28;
extern short var_29;
extern unsigned long long int var_30;
extern signed char var_31;
extern _Bool var_32;
extern _Bool var_33;
extern unsigned short var_34;
extern int var_35;
extern unsigned int var_36;
extern short var_37;
extern short arr_3 [15] [15] ;
