extern unsigned char var_10;
extern short var_11;
extern unsigned short var_12;
extern unsigned char var_13;
extern short var_14;
extern unsigned char var_15;
extern long long int var_16;
extern short var_17;
extern unsigned char arr_10 [19] ;
extern unsigned char arr_11 [19] ;
