extern unsigned int var_15;
extern unsigned short var_16;
extern unsigned char var_17;
extern _Bool var_18;
extern short var_19;
extern short var_20;
extern signed char var_21;
extern unsigned char var_22;
extern unsigned short var_23;
extern unsigned short var_24;
extern unsigned char var_25;
extern unsigned char var_26;
extern unsigned long long int var_27;
extern _Bool var_28;
extern _Bool var_29;
extern unsigned char var_30;
extern unsigned char var_31;
extern int var_32;
extern _Bool var_33;
extern unsigned char var_34;
extern unsigned short var_35;
extern int var_36;
extern _Bool var_37;
extern long long int var_38;
extern unsigned char arr_9 [12] [12] ;
extern long long int arr_17 [12] [12] [12] ;
extern signed char arr_18 [12] [12] ;
extern unsigned char arr_19 [12] ;
