extern unsigned short var_18;
extern unsigned long long int var_19;
extern unsigned int var_20;
extern int var_21;
extern unsigned int var_22;
extern signed char var_23;
extern unsigned long long int var_24;
extern long long int var_25;
extern unsigned long long int var_26;
extern int var_27;
extern unsigned long long int var_28;
extern short var_29;
extern short var_30;
extern unsigned long long int var_31;
extern signed char var_32;
extern unsigned short var_33;
extern short var_34;
extern unsigned long long int var_35;
extern short var_36;
extern _Bool var_37;
extern signed char var_38;
extern long long int var_39;
extern long long int var_40;
extern unsigned int var_41;
extern int var_42;
