extern signed char var_15;
extern unsigned char var_16;
extern unsigned long long int var_17;
extern _Bool var_18;
extern unsigned char var_19;
extern signed char var_20;
extern unsigned short var_21;
extern unsigned int var_22;
extern signed char var_23;
extern unsigned int var_24;
extern long long int var_25;
extern unsigned long long int var_26;
extern unsigned short var_27;
extern long long int var_28;
extern int var_29;
extern long long int var_30;
extern unsigned char var_31;
extern unsigned int var_32;
extern unsigned long long int var_33;
extern unsigned char var_34;
extern unsigned int var_35;
extern _Bool var_36;
extern unsigned char var_37;
extern unsigned char var_38;
extern unsigned char var_39;
extern unsigned long long int var_40;
extern short var_41;
extern long long int var_42;
extern unsigned char var_43;
extern unsigned char var_44;
extern long long int var_45;
extern unsigned int var_46;
extern int var_47;
extern unsigned int var_48;
extern unsigned long long int var_49;
extern unsigned char var_50;
extern short var_51;
extern unsigned char var_52;
extern signed char var_53;
extern unsigned char var_54;
extern unsigned int var_55;
extern unsigned short var_56;
extern signed char var_57;
extern short var_58;
extern unsigned long long int var_59;
extern signed char var_60;
extern signed char var_61;
extern long long int var_62;
extern signed char var_63;
extern _Bool var_64;
extern _Bool var_65;
extern _Bool var_66;
