extern _Bool var_20;
extern _Bool var_21;
extern int var_22;
extern unsigned long long int var_23;
extern unsigned long long int var_24;
extern int var_25;
extern int var_26;
extern long long int var_27;
extern _Bool var_28;
extern unsigned short var_29;
extern int var_30;
extern int var_31;
extern int var_32;
extern int var_33;
extern int var_34;
extern unsigned long long int var_35;
extern int var_36;
extern unsigned short var_37;
extern int var_38;
extern _Bool var_39;
extern long long int var_40;
extern int var_41;
extern unsigned int var_42;
extern int var_43;
extern long long int var_44;
extern unsigned long long int var_45;
extern _Bool var_46;
extern long long int var_47;
extern _Bool var_48;
