extern unsigned int var_15;
extern unsigned int var_16;
extern unsigned int var_17;
extern unsigned short var_18;
extern unsigned int var_19;
extern unsigned short var_20;
extern unsigned short var_21;
extern unsigned short var_22;
extern unsigned int var_23;
