extern _Bool var_16;
extern signed char var_17;
extern unsigned short var_18;
extern long long int var_19;
extern unsigned char var_20;
extern int var_21;
extern _Bool var_22;
extern unsigned int var_23;
extern _Bool var_24;
extern _Bool var_25;
extern int var_26;
extern unsigned int var_27;
extern signed char var_28;
extern long long int var_29;
extern int var_30;
extern _Bool var_31;
extern short var_32;
extern unsigned char var_33;
extern short var_34;
extern short var_35;
extern _Bool var_36;
extern _Bool var_37;
extern unsigned short var_38;
extern _Bool var_39;
extern long long int var_40;
extern signed char var_41;
extern unsigned long long int var_42;
extern signed char var_43;
extern long long int var_44;
extern signed char var_45;
extern int var_46;
extern unsigned short var_47;
extern long long int var_48;
extern long long int var_49;
extern short var_50;
extern signed char var_51;
extern unsigned long long int var_52;
extern unsigned char var_53;
extern signed char var_54;
extern signed char var_55;
extern long long int var_56;
extern _Bool var_57;
extern unsigned int var_58;
extern _Bool var_59;
extern signed char var_60;
extern signed char var_61;
extern long long int var_62;
extern short var_63;
extern unsigned char var_64;
extern signed char var_65;
extern long long int var_66;
extern short var_67;
extern unsigned long long int var_68;
extern signed char var_69;
extern long long int var_70;
extern unsigned short var_71;
extern short var_72;
extern int var_73;
extern signed char var_74;
extern int var_75;
extern unsigned long long int var_76;
extern signed char var_77;
extern signed char var_78;
extern int var_79;
extern long long int var_80;
extern _Bool var_81;
extern unsigned short var_82;
extern unsigned short var_83;
extern long long int var_84;
extern short var_85;
extern long long int var_86;
extern unsigned int var_87;
extern unsigned short var_88;
extern long long int var_89;
extern long long int var_90;
extern int var_91;
extern _Bool var_92;
extern _Bool var_93;
extern _Bool var_94;
extern _Bool var_95;
extern unsigned char var_96;
extern signed char var_97;
extern unsigned long long int var_98;
extern unsigned char var_99;
extern unsigned char var_100;
extern short var_101;
extern unsigned short var_102;
extern signed char var_103;
extern _Bool var_104;
extern int var_105;
extern signed char var_106;
extern signed char var_107;
extern _Bool var_108;
extern _Bool var_109;
extern signed char var_110;
extern long long int var_111;
extern long long int var_112;
extern _Bool var_113;
extern signed char var_114;
extern signed char var_115;
extern signed char var_116;
extern signed char var_117;
extern long long int var_118;
extern int var_119;
extern long long int var_120;
extern unsigned char var_121;
extern unsigned long long int var_122;
extern unsigned int var_123;
extern signed char var_124;
extern _Bool var_125;
extern _Bool var_126;
extern signed char var_127;
extern long long int var_128;
extern unsigned char var_129;
extern _Bool var_130;
extern _Bool var_131;
extern unsigned char var_132;
extern signed char var_133;
extern unsigned char var_134;
extern unsigned long long int var_135;
extern int var_136;
extern short var_137;
extern unsigned short var_138;
extern short var_139;
extern long long int var_140;
extern long long int var_141;
extern signed char var_142;
extern int var_143;
extern _Bool var_144;
extern unsigned int var_145;
extern _Bool var_146;
extern signed char var_147;
extern signed char var_148;
extern _Bool var_149;
extern long long int var_150;
extern unsigned long long int var_151;
extern short var_152;
extern short var_153;
extern signed char var_154;
extern _Bool var_155;
extern long long int var_156;
extern short var_157;
extern _Bool var_158;
