extern _Bool var_15;
extern long long int var_16;
extern _Bool var_17;
extern long long int var_18;
extern unsigned long long int var_19;
extern unsigned char var_20;
extern _Bool var_21;
extern short var_22;
extern long long int var_23;
extern int var_24;
extern unsigned short var_25;
extern int var_26;
extern unsigned short var_27;
extern _Bool var_28;
extern unsigned short var_29;
extern long long int var_30;
extern long long int var_31;
extern unsigned char var_32;
extern long long int var_33;
extern unsigned short var_34;
extern _Bool var_35;
extern unsigned short var_36;
extern short var_37;
extern unsigned int var_38;
extern unsigned short var_39;
extern unsigned short var_40;
extern short var_41;
extern int var_42;
extern _Bool arr_4 [21] [21] ;
extern short arr_5 [21] ;
extern signed char arr_15 [21] [21] [21] [21] [21] ;
extern int arr_24 [23] [23] [23] ;
extern _Bool arr_25 [23] ;
