extern signed char var_16;
extern _Bool var_17;
extern unsigned short var_18;
extern int var_19;
extern unsigned long long int var_20;
extern long long int var_21;
extern int var_22;
extern unsigned long long int var_23;
extern unsigned short var_24;
extern unsigned char var_25;
extern unsigned short var_26;
extern unsigned int var_27;
extern unsigned short var_28;
extern short var_29;
extern unsigned short var_30;
extern short var_31;
extern unsigned short var_32;
extern unsigned long long int var_33;
extern unsigned long long int arr_18 [10] [10] [10] ;
extern short arr_19 [10] [10] ;
